name: Release
on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2

      - uses: actions/setup-node@v2
        with:
          cache: 'yarn'

      - run: yarn install

      - name: Semantic Release
        run: yarn semantic-release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
